In [92]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.22.4


In [93]:
def FizzBuzz(x):
    ans = []
    return ans

In [94]:
def FizzBuzz(x):
    if x % 3 == 0 and x % 5 != 0:
        return "Fizz!"
    elif x % 5 == 0 and x % 3 != 0:
        return "Buzz!"
    elif x % 3 == 0 and x % 5 == 0:
        return "FizzBuzz!"
    else:
        return "..."
        print(FizzBuzz(5))
print(FizzBuzz(-30))

FizzBuzz!


In [95]:
def FizzBuzzList(n):
    if n <= 0:
        return []
    else:
        result = []
        for i in range(1, n+1):
            if i % 3 == 0 and i % 5 != 0:
                result.append("Fizz!")
            elif i % 5 == 0 and i % 3 != 0:
                result.append("Buzz!")
            elif i % 3 == 0 and i % 5 == 0:
                result.append("FizzBuzz!")
            else:
                result.append("...")
        return result
print(FizzBuzzList(5))


['...', '...', 'Fizz!', '...', 'Buzz!']


In [96]:
def standarize(X):
    mean = np.mean(X)
    std_dev = np.std(X)
    z_scores = (X - mean) / std_dev
    return z_scores
print(standarize)


<function standarize at 0x7feb3f389d30>


In [107]:
import numpy as np

def main_diagonal_matrix(A):
    D = np.diag(np.diag(A)).astype(float)
    return D

In [99]:
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]

])
print(A)

[[1 0 2 9 2]
 [9 2 6 5 7]
 [6 4 3 4 7]]


In [100]:
A([
    [4, 0, 2],
    [9, 5, 6],
    [1, 9, 6],
    [3, 0, 5]

])
print(main_diagonal_matrix)

[[4 0 2]
 [9 5 6]
 [1 9 6]
 [3 0 5]]
